### ISSUE TITLE
Weird behavior on Angular 10 and Material 10

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ShankyTiwari/ng-material-multilevel-menu#131]
Hi,

**_Use case 1:_**

`expandCollapseStatus = 'expand';`

You can see that it has weird behaviors:

1. Need to click 2 times to expand/collapse.

2. When I clicked the top menu item it expands the bottom menu item and vice versa

3. I can't collapse all menu items

Please see the video:

Youtube Video: https://youtu.be/LsRAl25Xv1I

**Use case 2:**

`expandCollapseStatus = 'collapse';`

You can see that it has weird behaviors:

1. Need to click 2 times to expand.

2. When I clicked the inner item then it auto collapsed the parent. i.e. I cannot go to the inner menu items.

Please see the video:

Youtube Video: https://youtu.be/ktBUS9U4BSI

Sample Git repo: https://github.com/Sampath-Lokuge/Angular-10.git

**Note:** You can see the implementation on `app.component.html/ts` files.

**Comment by ShankyTiwari** [comment]
Hi @Sampath-Lokuge, Sorry for the delay.

Thanks for reporting this issue, it was major issue and unfortunately I missed it. I have changed the implementation of this feature slightly, you can find it [here](https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo/blob/master/src/app/pages/more-configuration/expand-collapse/expand-collapse.component.ts#L73), now it should be fixed in [5.0.1](https://www.npmjs.com/package/ng-material-multilevel-menu/v/5.0.1#1-exapand-collapse-all-menu).

Let me know in case of any issue.

Thanks
