### ISSUE TITLE
can we use children instead of items in the collections, and also what if we can do for two way binding

### ISSUE THREAD

**Issue by karthikn21** [ShankyTiwari/ng-material-multilevel-menu#56]

**Comment by ShankyTiwari** [comment]
Hi @karthikn21,
1. Can we use children instead of items in the collections: 
=> Nope, sorry I'll have to do a lot of changes for that.

2.  If we can do for two way binding: 
=> I don't clearly understand your intent here. However, if you want to update the menus based on some conditions (assume, if you have a text box and based on user's input if you want to change the Menu's label) you can easily do that. 
For example,
```javascript
setInterval( () => {
      this.appitems[0]['items'][1]['items'][0]['label'] = `Dynamic Label - ${Math.random() * 10}`;
      console.log(this.appitems);
    }, 2000);
```
Take a look at output,
![Dynamic Menus](https://user-images.githubusercontent.com/15548024/60767784-312f2a00-a0da-11e9-9415-60da9736f3b8.gif)

And please do use `ChangeDetectionStrategy.Default`. As of now am closing the issue, if I was not clear, feel free to reopen the issue.

Thanks
