### ISSUE TITLE
Selecting the menu item with the link parameter.

### ISSUE THREAD

**Issue by MehmetSert** [ShankyTiwari/ng-material-multilevel-menu#79]
Hello,

When defining the menu item;
```
{
      label: 'Customers',
      imageIcon: `assets/svg/menu/customers.svg`,
      items: [
        {
          label: 'All Customers',
          link: '/dashboard/customers/all'
        },
        {
          label: 'New Customer',
          link: '/dashboard/customers/new'
        }
      ]
}
```

My routing definition is like this;;
```
{
        path: 'customers',
        children: [
          { path: 'all', component: CustomerComponent },
          { path: 'new', component: NewCustomerComponent },
          { path: 'detail/:id', component: CustomerDetailComponent }
        ]
}
```

This is how we define, and for example, when I'm in my project on the /dashboard/customers/new page, this menu is selected. No trouble here.

However, I go to /dashboard/customers/detail/{id} and show the customer detail. Is there a way to bring the menu selected when I go to this page?

Thanks in advance.

**Comment by ShankyTiwari** [comment]
I am aiming to solve this in coming weekend @MehmetSert.

**Comment by MehmetSert** [comment]
Unfortunately, it didn't. I added the following object in the array of menu elements;
{
           label: 'Customer Detail',
           link: '/dashboard/customers/detail/{id}'
}

When I open the link http: // localhost: 4200 / dashboard / customers / detail / 3, the menu does not appear selected.

**Comment by ShankyTiwari** [comment]
Hi @MehmetSert ,

here you have to et URL as shown below, this `/dashboard/customers/detail/{id}` wont work.
```javascript
{
           label: 'Customer Detail',
           link: '/dashboard/customers/detail/3'
}
```

Sorry for the delay in replying.

Thanks

**Comment by afunworm** [comment]
Hello.

I am running into the same issue. I am aware that I can try to set the URL in the `link` but:

Let's say I have the route set up as above:

```
{
      label: 'Customers',
      items: [
        {
          label: 'All Customers',
          link: 'customers/all'
        },
        {
          label: 'Edit Customer',
          link: 'customers/edit'
        }
      ]
}
```

And the route definition:

```
{
        path: 'customers',
        children: [
          { path: 'all', component: CustomerComponent },
          { path: 'edit', component: EditCustomerComponent },
          { path: 'edit/:id', component: EditCustomerDetailComponent }
        ]
}
```

Is it better to have the module highlight the `Edit Customer` link when either `customers/edit` or `customers/edit/random_customer_id` or even `customers/edit/random_customer_id/name` is routed to? In the end, the first one is the parent route of all the children, and they all contains `customers/edit`, the rest is just anything (think of it as `customers/edit/*`).

I actually have been trying to manually check the URL and changing the `navItems` according to the loaded URL, but the issue is that if you change the `link` inside the `navItems` array, it affects the routing of it too. For example:

```
navItems = {
      label: 'Customers',
      items: [
        {
          label: 'All Customers',
          link: 'customers/all'
        },
        {
          label: 'Edit Customer', //Every time this link is click, angular route to customers/edit - Expected
          link: 'customers/edit'
        }
      ]
}

ngOnInit() {
      //Detect the child URL so that if it is 'customers/edit/customer_id', highlight 'Edit Customers'
      if (current_route_is_edit_user_with_customer_id()) {
            //Quick & dirty way to demonstrate my point only
            this.navItems.items[1].link = 'customers/edit/' + get_customer_id_from_url();
            //Now the highlight works, because the `link` has been updated.
            //HOWEVER, clicking on this link will now navigate to `customers/edit/id` instead of `customers/edit`...
      }
}
```

As you can see, there's no built-in method to highlight the link manually without changing the link, and even if we manage to highlight the link manually, the route target changes. There's no way I can think of that can help achieve this task.

I really do think this is some good default behavior to have, because most of the links will have nested children and the children might have children and so on. Why doesn't it just checks if the link starts with the path, and highlight it?

Please advise.

**Comment by ryhahn1** [comment]
Hello, 

I am running into this same issue. Is there a fix or a work around for this?
