### ISSUE TITLE
Is this not working on IE 11

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ShankyTiwari/ng-material-multilevel-menu#87]
Hi,

I have tried to open your demo on IE 11 and it is not working. Is this not working on IE 11? Since Angular Material is working fine on IE 11 I hope the issue is on your module?

![IE 11 Issue](https://i.imgur.com/QbFe40O.png)

**Comment by ShankyTiwari** [comment]
Hi @Sampath-Lokuge , The [https://plugins.codershood.info/](https://plugins.codershood.info/) won't work in IE because it not compiled in `es5`.  But the plugin should work since I have now compiled in `es5`.

Also, I will urge to you check out [this repo](https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo) and you can open this [demo](https://multilevel-menu-demo.web.app/) as on IE. The demo is working on IE.

Thanks
